version = "3.9.0"

lineEndings = preserve
trailingCommas = multiple
maxColumn = 120
assumeStandardLibraryStripMargin = no
includeNoParensInSelectChains = yes

align {
  stripMargin = yes
  preset = most
  multiline = true
  arrowEnumeratorGenerator = true
  openParenCallSite = false
  openParenDefnSite = true
  openBracketDefnSite = true
}

docstrings {
  forceBlankLineBefore = no
  oneline = keep
  style = SpaceAsterisk
  wrap = no
}

spaces {
  inImportCurlyBraces = true
  beforeContextBoundColon = IfMultipleBounds
  inInterpolatedStringCurlyBraces = false
}

indentOperator {
  exemptScope = all
}

newlines {
  source = keep
  selfAnnotation = true
  alwaysBeforeMultilineDef = false
  implicitParamListModifierPrefer = before
  beforeCurlyLambdaParams = multilineWithCaseOnly
  inInterpolation = "avoid"
  afterCurlyLambdaParams = squash
  topLevelBodyIfMinStatements = [before, after]
  topLevelBodyMinStatements = 2
  topLevelStatementBlankLines = [
    { blanks = 1 }
  ]
}

rewrite {
  trailingCommas.style = multiple
  rules = [
    PreferCurlyFors
    SortModifiers
    AvoidInfix
    RedundantParens
    RedundantBraces
    Imports
  ]
  redundantBraces {
    generalExpressions = true
    stringInterpolation = true
    methodBodies = true
    includeUnitMethods = false
    ifElseExpressions = true
  }
  imports {
    expand = false
    sort = scalastyle
    groups = [
      ["com\\.airgradient\\..*"],
      ["izumi\\..*"],
      ["distage\\..*"],
      ["sttp\\..*"],
      ["ox\\..*"],
      ["com\\.github\\.pureconfig\\..*"],
      ["com\\.github\\.plokhotnyuk\\..*"],
      ["scala\\..*"],
      ["java\\..*"],
    ]
  }
  sortModifiers.order = [
    implicit, final, sealed, abstract, private, protected, lazy,
    transparent, inline, infix, opaque, override, open
  ]
}

rewriteTokens {
  "⇒" = "=>"
  "→" = "->"
  "←" = "<-"
}

runner {
  dialect = scala3
  dialectOverride {
    allowSignificantIndentation = true
    allowAsForImportRename = true
    allowStarWildcardImport = true
  }
}

literals {
  long = Upper
  float = Lower
  double = Lower
  hexDigits = Lower
  hexPrefix = Lower
  scientific = Lower
}

project {
  git = true
  includeFilters = [
    ".*\\.scala$"
    ".*\\.sbt$"
    ".*\\.sc$"
  ]
  excludeFilters = [
    "target/.*"
    ".*/target/.*"
  ]
}
