aether {
  server {
    host = "0.0.0.0"
    host = ${?SERVER_HOST}
    port = 8080
    port = ${?SERVER_PORT}
  }
  airgradient {
    base-url = "http://192.168.1.100"
    base-url = ${?AIRGRADIENT_BASE_URL}
    poll-interval-ms = 30000
    poll-interval-ms = ${?AIRGRADIENT_POLL_INTERVAL_MS}
    timeout-ms = 5000
    timeout-ms = ${?AIRGRADIENT_TIMEOUT_MS}
  }
}
