global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429'] # http://vmagent:8429/metrics
  - job_name: 'currency_scrapper'
    static_configs:
      - targets: ['http://192.168.1.35:8000']
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert:8880'] # http://vmalert:8429/metrics
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428'] # http://victoriametrics:8429/metrics